baseURL = "https://chidiwilliams.com/"
languageCode = "en-us"
title = "Chidi Williams"
theme = "chidiwilliams"
googleAnalytics = "UA-167812981-1"
disqusShortname = "chidiwilliams"

[params]
description = "Posts from Chidi Williams, a software engineer from Lagos, Nigeria."
images = [
  "https://res.cloudinary.com/cwilliams/image/upload/v1592140043/chidiwilliams_-_twitter_icon_small.png"
]

[markup.highlight]
style = "xcode"

[taxonomies]
category = "categories"
series = "series"
tags = "tags"
